### ISSUE TITLE
IMPROVEMENTS sprint 02-toolsurvey

### ISSUE THREAD

**Issue by pmjklemm** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#103]
https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Software-Development/02-toolsurvey

- link to license
- format nicely (header size)

**Comment by nighthog80** [comment]
added links to licence definitions

**Comment by KK-NFDI** [comment]
@nighthog80 @pmjklemm This has been realized, right? Can we close the issue?

**Comment by nighthog80** [comment]
yes
