### ISSUE TITLE
Add microbiology examples for licensed data

### ISSUE THREAD

**Issue by konrad** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#111]
Add microbiology examples for licensed data and explain the licensed used there.

**Comment by MartinBoleSlo** [comment]
Possible examples from Zenodo:
Metagenome-assembled genomes (MAGs), colorectal cancer (CRC) (https://zenodo.org/records/7008911) - CC BY 4.0

Metagenome assemblies and metagenome-assembled genomes from the Daphnia magna microbiota
Creators (https://zenodo.org/records/4435010) - CC BY 4.0

Data from: Mining for NRPS and PKS genes revealed a high diversity in the Sphagnum bog metagenome - (https://zenodo.org/records/4976456) - CC0 

Data from: Generational conservation of composition and diversity of field-acquired midgut microbiota in Anopheles gambiae sensu lato during colonization in the laboratory - (https://zenodo.org/records/5001400) - CC0
