### ISSUE TITLE
Content: Reshuffle RDM

### ISSUE THREAD

**Issue by KK-NFDI** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#117]
During the content sprint it was suggested to have the topics under "Research Data Management" follow the lables/steps provided in the/a data life cycle graphic. Big topics could still get their own page afterwards. This would require reshuffling content accordingly.

E.g. see the following mockup:
![image](https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/assets/115994792/74c09f7a-1861-4851-a71c-a5e743dccbc5)

It was also suggested to use the image and steps of (or similar to) the Elixir data life cycle https://rdmkit.elixir-europe.org/data_life_cycle

**Comment by nacnoriko** [comment]
another example:
https://www.gfbio.org/training/material/data-life-cycle
