### ISSUE TITLE
Need to generate a better starting page

### ISSUE THREAD

**Issue by elhossary** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#171]
Currently, there ware no index.md that the root calling should start from. As a part of fixing #91, I created it empty, and made it redirect to Getting-Started/01-introduction as used to be.

But this not a good practice, There should be a beautiful starting page with general info and visuals.

I created this issue to make content for it.

**Comment by pmjklemm** [comment]
duplicated, see #204
