### ISSUE TITLE
Create Github actions to deploy to the server of the official domain

### ISSUE THREAD

**Issue by elhossary** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#172]
I am admin-ing the server that which hosts this repo at https://knowledgebase.nfdi4microbiota.de
I do pulls from time to time to update it, which is a bad practice.
In order to create Github action to deploy on every push, I need access/permission to the repo settings to create the runners.
@konrad Who can do this?

**Comment by konrad** [comment]
I have gave you a role with more permission. Please check if this is sufficient.

**Comment by elhossary** [comment]
The settings tab appeared, but the sub-tab of github actions didn't. So I would say it is not suffient.
https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/adding-self-hosted-runners

**Comment by konrad** [comment]
Role changed again. Please try again.

**Comment by elhossary** [comment]
Done, the main branch now deploys to knowledgebase.nfdi4microbiota.de
