### ISSUE TITLE
integrate the kits reference properly to the page

### ISSUE THREAD

**Issue by cpauvert** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#183]
I spotted that the references in the Kit list page in "Experimental Procedure Standards SOPs" section are not actually included but copy-pasted, numbers are used for the references as well (see below)

![image](https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/assets/12406679/e5dc5173-eb38-40bc-91e9-cf0b1bc12620)

@saschulz or @KK-NFDI should I assigned one of you here?

Best,

**Comment by KK-NFDI** [comment]
This seems to be also the case for https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Experimental-Procedure-Standards-SOPs/06-metabolite-extraction-from-adherent-mammalian-cells.html
And
https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Experimental-Procedure-Standards-SOPs/07-metabolite-extraction-from-plant-tissue.html
as well as
https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Experimental-Procedure-Standards-SOPs/09-sample-collection-and-storage-by-sample.html

The reference for 
https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Experimental-Procedure-Standards-SOPs/08-proteomics-tmt-labelled-sp3-method.html
is given in another style. Is this intended?

For me it is not always clear where the reference should appear in the text.
@saschulz  could you have a look and replace the references?

There is an explanation how to do it at the bottom of https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Getting-Started/02-contributing.html

You could also have a look at pages with existing references, e.g. https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/blob/main/docs/_Research-Data-Management/04-fair.md , as a reference.

**Comment by saschulz** [comment]
@cpauvert do you mean that the references aren't hyperlinked?

@KK-NFDI regarding the protemics SOP that is how the proteomics core facility at embl asks to be cited 

I'll check the references

**Comment by cpauvert** [comment]
> @cpauvert do you mean that the references aren't hyperlinked?
> 
Hi! Well yes, but this is a consequence of the issue. I meant that the references are hard coded as text (13 is typed as is, instead of typing that this is the reference for Goolam et al. etc.) and not a part of the reference file  `docs/_bibliography/references.bib`. Let me know if I can provide more details. Best,

**Comment by cpauvert** [comment]
> This seems to be also the case for [...]

Good catch thanks! Do you want to create issues for each of them or a [general issue with tasks lists](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#about-issue-task-lists) so that we do not forget to fix them? THat would be great :)

> You could also have a look at pages with existing references, e.g. https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/blob/main/docs/_Research-Data-Management/04-fair.md , as a reference.

Good point, even if the instruction to cite is actually not visible.

```
Cite the reference in the text using (missing reference)
```

**Comment by magelm** [comment]
Hey, 
it looks like one of you has already solved the referencing issues for all the mentioned documents:

- [x] https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Experimental-Procedure-Standards-SOPs/04-dna-and-rna-kits-by-sample.html

- [x] https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Experimental-Procedure-Standards-SOPs/06-metabolite-extraction-from-adherent-mammalian-cells.html

- [x] https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Experimental-Procedure-Standards-SOPs/07-metabolite-extraction-from-plant-tissue.html


- [x] https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Experimental-Procedure-Standards-SOPs/09-sample-collection-and-storage-by-sample.html

- [x] https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Experimental-Procedure-Standards-SOPs/08-proteomics-tmt-labelled-sp3-method.html

Thank you so much! I'll close this issue for you :)
