### ISSUE TITLE
Link for NFDI4Microbiota domain on biotools is broken

### ISSUE THREAD

**Issue by catgonzftw1** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#214]
The link for the NFDI4Micro biotools is broken on the knowledge base page: https://knowledgebase.nfdi4microbiota.de/Software-Development/02-toolsurvey.html

**Comment by nighthog80** [comment]
checking

**Comment by MartinBoleSlo** [comment]
If I am not to late, I am already working on this, along with updating all of the broken links, and removing the duplicates
