### ISSUE TITLE
Improving citation

### ISSUE THREAD

**Issue by jvddorpe** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#231]
For the citation at the bottom of each page, it would be great if the date was the date that specific page was last modified, rather than the date that a change was made to the Knowledge Base. It would also be nice to add the URL of the specific page at the end of the citation. For example, National Research Data Infrastructure for Microbiota Research (NFDI4Microbiota). (2024, August 13). Research Data. NFDI4Microbiota Knowledge Base. https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Research-Data-Management/01-rd.html

**Comment by compbioldev** [comment]
Added the date of first publication of the website tracked using archive.org / waybackmachine for external pages.
