### ISSUE TITLE
Link the helpdesk at the bottom of each page

### ISSUE THREAD

**Issue by jvddorpe** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#234]
It would be great if, on each page of the Knowledge Base, right above "Citation", there would be a section "Get Help" with the following content: "If you have any further questions about the management and analysis of your microbial research data, please contact us: helpdesk@nfdi4microbiota.de (by emailing us you agree to the privacy policy on our website: [Contact](https://nfdi4microbiota.de/contact-form/))".

**Comment by jvddorpe** [comment]
Thanks @MartinBoleSlo! On the ELN page, the "Get Help" section is inserted within the "Resources" section instead of after it. Could you fix this?

**Comment by MartinBoleSlo** [comment]
Hi @jvddorpe I think It is still at that place, because my pull request is not merged yet to main =) Should be fine after the merging =) will double check tomorrow after merge, issue stays open

**Comment by jvddorpe** [comment]
Hi @MartinBoleSlo thanks for your reply! :)
