### ISSUE TITLE
Display is not dynacic

### ISSUE THREAD

**Issue by KK-NFDI** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#64]
The display of the knowledge base is not dynamic with regards to screen resolution.
On lower resolutions the content overlaps.
Width 1920px:
![scrollbar](https://user-images.githubusercontent.com/115994792/212293932-853aa64e-5906-4235-a5dd-4cb89108b464.png)

Width 1024px:
![1024Resolution](https://user-images.githubusercontent.com/115994792/212294066-d2815345-f884-4f5a-9251-76cf12c29397.png)

At least for reasonable screen resolutions, this should be displayed correctly. This is also relavant for displaying the knowledge base on mobile devices.

**Comment by Xiart** [comment]
The issue has been resolved. Kindly have a look

**Comment by KK-NFDI** [comment]
Hi @Xiart , I found/opened two issues https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/issues/82 https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/issues/81 that I assume were introduced with the changes for this.

**Comment by KK-NFDI** [comment]
@Xiart And one more: https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/issues/83
