### ISSUE TITLE
contributing.md missing/ wrongly linked

### ISSUE THREAD

**Issue by magelm** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#77]
Hey, 

the  md.s in the readme file for contributing are either corrupted or have been deleted/ moved. 
Please double-check: https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/blob/main/README.md 

Thank you!
Maja

**Comment by KK-NFDI** [comment]
Hi @magelm thanks for noticing. 
I just created a pull request to fix this ( https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/pull/78 )

**Comment by KK-NFDI** [comment]
Merged.
