### ISSUE TITLE
Error 404 document link

### ISSUE THREAD

**Issue by magelm** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#79]
Hey, 

there is an error 404 for the document link under the heading "[Fair principles for Data management](https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Reproducible-Data-Analysis/02-workflows#fair-principles-for-data-management)" in the first sentence.

Thank you for fixing it. 
Best, Maja

**Comment by KK-NFDI** [comment]
Hi @mahdi-robbani , given this ticket and https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/issues/77 it might be a good idea to run the script to find broken links again?

**Comment by KK-NFDI** [comment]
Addressed in https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/pull/80

**Comment by KK-NFDI** [comment]
Merged. @magelm Thanks for reporting.
