### ISSUE TITLE
Bug: The "empty" field seems to be ignored.

### ISSUE THREAD

**Issue by KK-NFDI** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#81]
The original behavior behind/intention for the "empty: true" field in the individual markdown files` headers was to gray out the listing on the knowledge base. This is meant to visualize missing information/uninformative pages.

This is no longer the case. 
I assume that the changes for https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/issues/64 caused this.

There is also a field "hide" for which "hide: true" does not seem to do anything.

**Comment by Xiart** [comment]
I just wanted to clarify few things

1. Should we list the file in the menu, have no content inside? I think they are purposely placed there allowing the users to be contributing.
2. I have removed the files from the menu where we have hide = true (should I keep it like that?) the menu looks like this now:
![image](https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/assets/55190458/c7c368fb-a6e9-4630-89f4-1213c692716c)

**Comment by KK-NFDI** [comment]
@Xiart I think that might be the idea for _hide_, yes.
Those that are empty but should be shown should have empty: true hide: false (which is the default).

Those that have empty: true, hide: false, schould be displayed such that users can contribute. Their menu entry should be displayed in a light-gray text color though.

At least this was the previous behavior.

**Comment by Xiart** [comment]
I have got it. Pushing the changes. 

Thank you.

**Comment by KK-NFDI** [comment]
@Xiart This issue has been closed, but the problem still persists (or appeared again).
