### ISSUE TITLE
setup github actions to help during the sprint (and after)

### ISSUE THREAD

**Issue by cpauvert** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#89]
Hello there, 
the sprint for the KB is going to see various contributions and changes, so it could be useful to have automated checks to make the KB consistent.

A few that comes to mind for markdown based project:

- A spell check that works for markdown files <https://github.com/marketplace/actions/github-spellcheck-action>
- A bad link reporter <https://github.com/caltechlibrary/baler>
- A Markdown linter <https://github.com/marketplace/actions/markdownlint-cli2-action>
- (optional) Adding alt text for image to improve accessibility <https://github.com/marketplace/actions/markdown-accessibility>

Let me know what you think,
Best,

**Comment by mahdi-robbani** [comment]
I added the CI checks but made them optional since people still might want to force changes even if the linter fails. Feel free to modify any settings, I'll close the issue for now
