### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by catgonzftw1** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#91]
When I go to the Knowledge Base site and I start on this page:

![image](https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/assets/120124695/e748c828-814b-45f6-b367-cf9d1af49111)

Then I click on the link "Contributing to the NFDI4Microbiota Knowledge Base" and I'm taken to that page. But then when I click the option "NFDI4Microbiota Knowledge Base" to go back, I get the following error:

![image](https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/assets/120124695/48f87cab-b4eb-4d1d-a0cf-9a2a9725efa4)

**Comment by mahdi-robbani** [comment]
TODO: Tag @elhossary

This link works correctly on the subdomain branch so I assume the issue is related to hosting it on the ZBMed server. The permalink of the page is set to `/` but can be changed if required.

**Comment by elhossary** [comment]
@mahdi-robbani 
I had fixed it in my local commits, but currently I have no permission to push the commits.

**Comment by elhossary** [comment]
Fixed.
However, the actual underlying problem is the fact that the website does not have an index page which the engine try to find it by default when the root is called.

For now, I created an empty index.md and made it redirect to the /Getting-Started/01-introduction.html
