### ISSUE TITLE
Missing: RNA-seq in data quality overview sidebar

### ISSUE THREAD

**Issue by magelm** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#92]
The header "RNAseq" for the [data quality control topic](https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Research-Data-Management/13-data-qc) doesn't seem to be properly hyperlinked. It's not included in the right-hand side overview "On this page".

**Comment by mahdi-robbani** [comment]
As far as I'm aware, this is by design since you can already see the first header when you load the page and you're just supposed to use the scrollspy to jump down to other content, but I've fixed this.
