### ISSUE TITLE
Metadata needed for individual SOPs

### ISSUE THREAD

**Issue by magelm** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#94]
The SOPs, e.g. [Viral purification from bacterial culture](https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/Experimental-Procedure-Standards-SOPs/03-viral-purification-from-bacterial-culture), are missing metadata.
If the goal is to promote the use of certain protocols, then as a reader (and potential user) I would need information on:

- suggested & created & amended by
-- & date
- used by (labs, institutions etc.); whom to contact for protocol usage questions
- references, including the material & kits (if applicable)
-- hyperlinked origin of protocol, DOI
-- ideally: reference to chemical compounds (e.g. [methanol](https://pubchem.ncbi.nlm.nih.gov/compound/methanol))

**Comment by Kobert** [comment]
@saschulz I think you set these pages up, right? Could you have a look if this is feasible?
