### ISSUE TITLE
Clarify: Intentions behind (external) SOPs

### ISSUE THREAD

**Issue by magelm** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#95]
Content is missing for [introduction](https://knowledgebase.nfdi4microbiota.de/Experimental-Procedure-Standards-SOPs/01-introduction.html) and for [external SOP](https://knowledgebase.nfdi4microbiota.de/Experimental-Procedure-Standards-SOPs/02-external-sops.html).

As a reader, I'm missing information on:

- why these SOPs are suggested
- where the difference between external SOPs and the other SOPs is:
![image](https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/assets/101332248/a74dd173-442f-4eca-afc4-4bd5865d7ec8)

- recommendation on how to cite, if a researcher uses the protocols (if we intend for people to use these)

**Comment by Kobert** [comment]
I think I added the External SOPs page a while back. If it is not needed we can delete or hide it. The intention was to list links to SOPs that we would not present in full here.

@saschulz could you add some content into the "Introduction" page on how to use the SOPs presented here?

**Comment by KK-NFDI** [comment]
A small introduction has been added during the content sprint. Some explanation from @saschulz about where the SOPs come from would still be good to add.

I hid the External SOPs page from view for now ("hide: true"). Changes can still be made to this file and if content is added, this flag can be set back to false.
