### ISSUE TITLE
Discrepancy between knowledge base 

### ISSUE THREAD

**Issue by magelm** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#96]
There seem to be different versions openly available of the knowledge base:

- I landed on the knowledge base by following the service header on the [N4M webpage](https://nfdi4microbiota.de/) and landed here: https://knowledgebase.nfdi4microbiota.de/ 
- The content there is different, than when I follow the link on the github (under "About") to https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/ 
-> ![image](https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/assets/101332248/9d66ee01-7fda-4408-bcfd-9a0ef2b32d66)

### Discrepancies include:

- [ ] broken vs. working link under "Getting Started/The NFDI4Microbiota Knowledge Base"(https://knowledgebase.nfdi4microbiota.de/.html) > [issue 91](https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/issues/91)
- [ ] different amount of SOPs

### Clarification/ discussion is needed:

- Is https://knowledgebase.nfdi4microbiota.de/ supposed to be the user-accessible and **clean** version of our knowledge base?
-- If yes, then: Should we delete the incomplete parts of the knowledge base to present a "finished knowledge base" product, instead of a work-in-progress display (which people can already access under https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/ ?
-- If not, then: Why do 2 inconsistent webpages exist in the first place?
--- Information on status of last updated might be needed for https://knowledgebase.nfdi4microbiota.de/ and a link pointing to the most updated version to be found on https://nfdi4microbiota.github.io/nfdi4microbiota-knowledge-base/

**Comment by Kobert** [comment]
Related, there is an old PR from @mahdi-robbani regarding the move: https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base/pull/85

@Xiart @elhossary Could either of you review, and if everything is fine, approve this PR

**Comment by mahdi-robbani** [comment]
> Related, there is an old PR from @mahdi-robbani regarding the move: #85
> 
> @Xiart @elhossary Could either of you review, and if everything is fine, approve this PR

We just need to add a CI job that builds that pages and uploads them to the ZBMed servers. The repo for the main NFDI website already has code for this but I'm not sure if that's meant to be public.

**Comment by elhossary** [comment]
Done, main branch now deploys to knowledgebase.nfdi4microbiota.de

**Comment by cpauvert** [comment]
> Done, main branch now deploys to knowledgebase.nfdi4microbiota.de with fixes for the mentioned discrepancies.
> 
thanks @elhossary 
> Now, I suggest to make the github pages to reflect dev branch so we can preview updates before it goes production by merging to the main

IMO that's a good idea, especially since a couple of issues (#117 or #118) might disrupt usual navigation, so this is a good alternative for those that cannot run and compile the KB locally (speaking of which, this is actually not documented on the README or contributing page). What do you think @Xiart @mahdi-robbani @konrad ?

**Comment by mahdi-robbani** [comment]
Sounds good to me
